### ISSUE TITLE
Elephant client causing a warning on Mastodon startup

### ISSUE THREAD

**Issue by stefanhahmann** [elephant-track/elephant-client#8]
# Bug Description

1. Activate "Mastodon" Update site (tested version mastodon-1.0.0-beta-26.jar)
2. Activate "ELEPHANT" Update site (tested version elephant-0.4.3.jar)
3. Restart Fiji
4. Open Plugin Mastodon

The following warning occurs:

![elephant bug](https://github.com/elephant-track/elephant-client/assets/10515534/edd255cb-8730-40b2-ad1c-0543ae1bcd23)

[elephant bug.txt](https://github.com/elephant-track/elephant-client/files/13530036/elephant.bug.txt)

Afterwards everything still seems to work as expected (as far as I am aware of). However, the warning is a bit annoying for users.

**Comment by stefanhahmann** [comment]
@ksugar any ideas on this?

**Comment by ksugar** [comment]
Hi @stefanhahmann, thank you for reporting the issue.
Because I did not set the log level to `debug`, I did not notice it.
I could reproduce the issue when I specified the log level as below.

```bash
/Applications/Fiji.app/Contents/MacOS/ImageJ-macosx -Dscijava.log.level=debug --
```

I guess it happens because `org.elephant.ElephantExtra.class` is included in the `compile` phase but excluded in the `package` phase. The extra modules were intended for a specific project, and I wanted to exclude them for public usage.

https://github.com/elephant-track/elephant-client/blob/3b278f78be4f833808340edbce31891d21cff367/pom.xml#L207

I will try excluding it in the `compile` phase using [maven-compiler-plugin](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#excludes).
